### ISSUE TITLE
Give Docker sudo permission

### ISSUE THREAD

**Issue by ataseren** [ErdemOzgen/DevSecOpsBuilder#29]
If Docker requires sudo in a device, install command doesn't work. Docker should be set with sudoers or users must be notified with adding Docker to sudoers list.

**Comment by ErdemOzgen** [comment]
Can give me exact location immediately makefile? I remembered as we give docker sudo permission but you might restart your computer.

**Comment by ataseren** [comment]
![image](https://github.com/ErdemOzgen/DevSecOpsBuilder/assets/63476820/7a31ddd9-48d9-4010-8d7e-89d26b2fade7)
Yes, there is the command for sudo permission but I had to enter it manually on my terminal. I also restarted my machine many times before manually entering this line. We should try to reproduce this bug on a fresh machine.

**Comment by ErdemOzgen** [comment]
Okay then restart will be solve this issue.
